WITH CTE2 AS 
(
WITH CTE AS 
(
SELECT EXTRACT(YEAR FROM TRANSACTION_DATE) AS TYEAR,
EXTRACT(month FROM TRANSACTION_DATE) AS TMONTH, CARD_TYPE, SUM(AMOUNT) AS SUM_AMOUNT
FROM credit_card_transcations
GROUP BY CARD_TYPE, EXTRACT(YEAR FROM TRANSACTION_DATE), EXTRACT(month FROM TRANSACTION_DATE)
)
SELECT *, MAX(SUM_AMOUNT) OVER (PARTITION BY CARD_TYPE ORDER BY SUM_AMOUNT ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS MAX_AMOUNT
FROM CTE
)
SELECT * FROM CTE2 WHERE SUM_AMOUNT = MAX_AMOUNT